### PR TITLE
Add PHP 7.3 to travis tests

### PR DESCRIPTION
**Pull request by ChrisOrlando**
7.3 is on RC5 now and Travis offers it, so I figured why not? 🤷‍♂️

### CODE REVIEW

**Comment by ChrisOrlando** [comment]
Looks like the 7.3 tests failed. 

```
PHPUnit 6.5.13 by Sebastian Bergmann and contributors.
Error:         No code coverage driver is available
```

Will try phpunit 7 in the off chance that it "just works."

**Comment by ChrisOrlando** [comment]
Using phpunit 7 makes the php 7.0 tests fail because phpunit 7 requires 7.1+.

Also 7.3 is still failing but each test failure says this:

```
Error: Class 'ApolloRip\BencodeTorrent\Bencode' not found
```

I think #2 might solve this. I'll leave this open so if #2 is merged and someone confirms tests for 7.0 aren't needed anymore, I can rebase this PR and remove the 7.0 tests.

**Comment by ChrisOrlando** [comment]
obsoleted by https://github.com/OPSnet/bencode-torrent/commit/911e2899f4682006545395aa4eb8fa1f30b29a15

**Comment by itismadness** [comment]
Sorry for not commenting on this sooner, I got distracted by Travis not properly building things.

Thanks for letting us know that PHP 7.3 was ready on Travis-CI, though I'm not sure what's going on with the errors with `Error:         No code coverage driver is available` for PHPUnit 7. Given PHP 7's EOL in a month, we plan to make a serious push to move Gazelle to be 7.1+ compatible and then drop 7.0 across all projects which means that we should be able to move to the new xenial dist on Travis and can better focus on debugging this particular issue if it continues.

**Comment by ChrisOrlando** [comment]
@itismadness Sounds good, thanks for checking into it. 👍

**Pull request closed without merging**
